import Header from '@/components/header/header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'HOMIIIE',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>My Exam-App</title>
      </head>
      <body className={inter.className}>
        <div className='header'>
          <Header/>
        </div>{children}</body>
    </html>
  )
}
